@startuml

actor Player

package "Banking : 8080" {
  node "Banking Service : 8080" as banking {
    [UserSliceService]
    [TransactionsSliceService]
  }

  database "Postgres Banking" {
    [User]
    [Transactions]
  }
}

package "Roulette : 8081" as Roulette {
  node "Roulette Service" as RouletteService {
    [Game] as RouletteGames
  }

  database "Postgres Roulette" {
    [Games] as RouletteGameTable
  }

  RouletteGames --> RouletteGameTable : Persist Games
}

package "Slot : 8082" as Slots {
  node "Slots Service" as SlotService {
      [Game] as SlotGames
  }

  database "Postgres Slots" {
    [Games] as SlotGame
  }

  SlotGames --> SlotGame : Persist Games
}

Player --> [UserSliceService] : HTTP\n CRUD
Player --> SlotGames : HTTP\n play slots
Player --> RouletteGames : HTTP\n play roulette

[UserSliceService] --> [User] : CRUD
TransactionsSliceService --> [Transactions] : CRUD
[TransactionsSliceService] --> [UserSliceService] : REST/HTTP POST deposit

SlotGames --> [TransactionsSliceService] : HTTP\n create transaction
RouletteGames --> [TransactionsSliceService] : HTTP\n create transaction

SlotGames --> [UserSliceService] : HTTP\n look up User
RouletteGames --> [UserSliceService] : HTTP\n look up User

@enduml