server:
  port: 8080
spring:
  application:
    name: Banking
  datasource:
    url: jdbc:postgresql://localhost:15432/banking
    username: postgresUser
    password: postgresPW
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

casino:
  services:
    bank:
      baseURL: ${CASINO_BANK_BASE_URL:http://localhost:8080/casino/bank/api}
    roulette:
      baseURL: ${CASINO_ROULETTE_BASE_URL:http://localhost:8081/casino/bank/api}
    slots:
      baseURL: ${CASINO_SLOTS_BASE_URL:http://localhost:8082/casino/bank/api}
