server:
  port: 8080
spring:
  application:
    name: Banking
  datasource:
    url: jdbc:postgresql://localhost:55432/banking
    username: postgresUser
    password: postgresPW
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update