@startuml

actor Player

package "Banking Service : 8080" as Banking {

package "User Slice" as UserServicePackage {
component "User Controller" as UserController
component "User Service" as UserService
component "User Repo" as UserRepo

UserController --> UserService
UserService --> UserRepo
}

package "Transaction Slice" as TransactionServicePackage {

component "Transaction Controller" as TransactionController
component "Transaction Service" as TransactionService
component "Transaction Repo" as TransactionRepo

TransactionController --> TransactionService
TransactionService --> TransactionRepo
}

TransactionService --> UserController : HTTP \n deposit

}

database "Postgres Banking" as BankingDB {
  [User] as UserTable
  [Transactions] as TransactionTable
}

node GameServices

UserRepo --> UserTable : persist User
TransactionRepo --> TransactionTable : persist Transactions

GameServices --> TransactionController : HTTP \n create Transactions
Player --> UserController : HTTP \n manage User

@enduml
