services:

  banking-db:
    container_name: Banking-PostgresDB
    profiles: [full, db]
    image: postgres:17
    environment:
      - POSTGRES_DB=banking
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
    ports:
      - "15432:5432"
    restart: unless-stopped
    volumes:
      - banking-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresUser -d banking" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

  banking-backend:
    profiles: [full]
    container_name: Banking-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://banking-db:5432/banking
      CASINO_BANK_BASE_URL: http://banking-backend:8080/casino/bank/api
    image: nilsscharein/casino-banking:1.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      banking-db:
        condition: service_healthy

volumes:
  banking-db-data:
