server:
  port: 8081
spring:
  application:
    name: Roulette
  datasource:
    url: jdbc:postgresql://localhost:15433/roulette
    username: postgresUser
    password: postgresPW
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update