services:

  slots-db:
    container_name: Slots-PostgresDB
    profiles: [full, db]
    image: postgres
    environment:
      - POSTGRES_DB=slots
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
    ports:
      - "55434:5432"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/backup/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresUser -d slots" ]
      interval: 30s
      timeout: 10s
      retries: 5

  slots-backend:
    profiles: [full]
    container_name: Slots-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://slots-db:5432/slots
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - slots-db

volumes:
  db-data:
